-- Lihat Database
SHOW DATABASES;
-- MENGGUNAKAN DATABASES MySQl
USE mysql;
-- melihat isi tabel dalam DB mysql
SHOW TABLES;
-- MELIHAT  DESKRIPSI DARI TABEL USER
DESCRIBE USER;
-- AMBIL ISI DARI KOLOM MOST, USER, PASWOORD
SELECT Most, User, Password FROM user